# Generated by Django 2.2.2 on 2020-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shopify_product_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('mrp', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('sku', models.CharField(db_index=True, max_length=50)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
