# Generated by Django 2.2.2 on 2020-03-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shopify_product_id', models.BigIntegerField(db_index=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('vendor', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('handle', models.CharField(max_length=500)),
                ('published_scope', models.CharField(max_length=200)),
                ('admin_graphql_api_id', models.CharField(max_length=200)),
                ('variable_product', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete='CASCADE', related_name='tags', to='products.Product')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Products Tag',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shopify_option_id', models.BigIntegerField(db_index=True, null=True)),
                ('option_name', models.CharField(max_length=100, unique=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('product_id', models.ForeignKey(on_delete='CASCADE', related_name='options', to='products.Product')),
            ],
            options={
                'verbose_name': 'Shopify Option',
                'verbose_name_plural': 'Shopify Options',
                'db_table': 'shopify_options',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shopify_image_id', models.BigIntegerField(db_index=True, null=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('src', models.URLField()),
                ('admin_graphql_api_id', models.CharField(max_length=500, null=True)),
                ('product_id', models.ForeignKey(on_delete='CASCADE', related_name='images', to='products.Product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('option', models.ForeignKey(on_delete='CASCADE', related_name='values', to='products.Option')),
            ],
            options={
                'verbose_name': 'Option Value',
                'verbose_name_plural': 'Option Values',
                'db_table': 'option_value',
                'unique_together': {('name', 'option')},
            },
        ),
    ]
