# Generated by Django 2.2.2 on 2020-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shopify_id',
            new_name='shopify_product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='variable_product',
            field=models.BooleanField(default=False),
        ),
    ]
