# Generated by Django 2.2.2 on 2020-03-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200307_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('product_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('product_id', 'position')},
        ),
    ]
