# Generated by Django 2.2.2 on 2020-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200307_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Product option',
                'verbose_name_plural': 'Products options',
                'db_table': 'option',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete='CASCADE', related_name='tag', to='products.Product')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Products Tag',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('option', models.ForeignKey(on_delete='CASCADE', related_name='option', to='products.Option')),
            ],
            options={
                'verbose_name': 'Option Value',
                'verbose_name_plural': 'Option Values',
                'db_table': 'option_value',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shopify_image_id', models.BigIntegerField(unique=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('src', models.URLField()),
                ('admin_graphql_api_id', models.CharField(max_length=500, null=True)),
                ('shopify_product_id', models.ForeignKey(on_delete='CASCADE', related_name='product', to='products.Product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
    ]
