# Generated by Django 2.2.2 on 2020-03-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200307_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shopify_varient_id', models.BigIntegerField(db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sku', models.CharField(max_length=200, null=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('inventory_policy', models.CharField(default='deny', max_length=40, null=True)),
                ('compare_at_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fulfillment_service', models.CharField(default='manual', max_length=40)),
                ('inventory_management', models.CharField(default='blank', max_length=40, null=True)),
                ('taxable', models.BooleanField(default=True)),
                ('barcode', models.CharField(max_length=200, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('weight_unit', models.CharField(choices=[('lb', 'lbs'), ('oz', 'oz'), ('kg', 'kilogram'), ('g', 'gram')], max_length=20, null=True)),
                ('inventory_quantity', models.IntegerField()),
                ('requires_shipping', models.BooleanField(default=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant', to='products.Image')),
                ('option1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant1', to='products.OptionValue')),
                ('option2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant2', to='products.OptionValue')),
                ('option3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant3', to='products.OptionValue')),
                ('product', models.ForeignKey(on_delete='CASCADE', related_name='variant', to='products.Product')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'db_table': 'variant',
            },
        ),
    ]
