# Generated by Django 2.2.2 on 2020-03-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200307_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='shopify_image_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='shopify_option_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopify_product_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='shopify_varient_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
