# Generated by Django 2.2.2 on 2020-03-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200307_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('product', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('product', 'option_name'), ('product', 'position')},
        ),
    ]
