# Generated by Django 2.2.2 on 2020-03-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200307_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
