# Generated by Django 2.2.2 on 2020-03-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200307_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='products.Option'),
        ),
    ]
