# Generated by Django 2.2.2 on 2020-03-08 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200307_2300'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'product')},
        ),
    ]
