# Generated by Django 2.2.2 on 2020-03-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200308_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='option',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='deleted',
        ),
    ]
