# Generated by Django 2.2.2 on 2020-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200308_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.CharField(max_length=100),
        ),
    ]
