# Generated by Django 2.2.2 on 2020-03-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shopify_cusomer_id', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('accepts_marketing', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=104)),
                ('last_name', models.CharField(blank=True, max_length=104)),
                ('orders_count', models.IntegerField()),
                ('state', models.CharField(max_length=64)),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_order_id', models.IntegerField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('verified_email', models.BooleanField(default=False)),
                ('multipass_identified', models.CharField(max_length=64, null=True)),
                ('tax_exempt', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('tags', models.TextField(null=True)),
                ('last_order_name', models.CharField(max_length=64, null=True)),
                ('currency', models.CharField(max_length=24)),
                ('marketing_opt_in_level', models.CharField(max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
    ]
