# Generated by Django 2.2.2 on 2020-02-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='order', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete='CASCADE', related_name='order_product', to='products.Product'),
        ),
    ]
