# Generated by Django 2.2.2 on 2020-03-08 10:43

import apps.orders.helpers
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('shopify_order_id', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.IntegerField()),
                ('note', models.TextField(null=True)),
                ('gateway', models.CharField(max_length=32, null=True)),
                ('test', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=9)),
                ('taxes_included', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=8)),
                ('financial_status', models.CharField(max_length=32)),
                ('confirmed', models.BooleanField(default=False)),
                ('total_discounts', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('total_line_items_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cart_token', models.CharField(max_length=32, null=True)),
                ('buyer_accepts_marketing', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('referring_site', models.URLField(max_length=2048, null=True)),
                ('landing_site', models.URLField(max_length=2048, null=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('total_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('order_number', models.IntegerField()),
                ('discount_applications', jsonfield.fields.JSONField(default=apps.orders.helpers.empty_list)),
                ('discount_codes', jsonfield.fields.JSONField(default=apps.orders.helpers.empty_list)),
                ('note_attributes', jsonfield.fields.JSONField(default=apps.orders.helpers.empty_list)),
                ('payment_gateway_names', jsonfield.fields.JSONField(default=apps.orders.helpers.empty_list)),
                ('processing_method', models.CharField(blank=True, max_length=32, null=True)),
                ('source_name', models.CharField(blank=True, max_length=32, null=True)),
                ('fulfillment_status', models.CharField(blank=True, max_length=32, null=True)),
                ('tax_lines', jsonfield.fields.JSONField(default=apps.orders.helpers.empty_list)),
                ('tags', models.CharField(blank=True, max_length=104, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_address', jsonfield.fields.JSONField(default=apps.orders.helpers.empty_dict)),
                ('shipping_address', jsonfield.fields.JSONField(default=apps.orders.helpers.empty_dict)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='orders.Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
    ]
