# Generated by Django 2.2.2 on 2020-03-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200308_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='multipass_identified',
            new_name='multipass_identifier',
        ),
    ]
