# Generated by Django 2.2.2 on 2020-03-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200308_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_order_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
