# Generated by Django 2.2.2 on 2020-03-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200308_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deleted',
        ),
    ]
